### ISSUE TITLE
DC Motor not working

### ISSUE THREAD

**Issue by Foggie200** [mjmeans/Adafruit.IoT#2]
Hi,

I tried to connect a DC motor to the shield and tried to run it using:

`.....
 MotorHat2348 mh = null;
       BackgroundTaskDeferral deferral;
         PwmDCMotor dc = null;

```
    public async void Run(IBackgroundTaskInstance taskInstance)
    {


        deferral = taskInstance.GetDeferral();

 // Create a driver object for the HAT at address 0x60
        mh = new MotorHat2348(0x60);

        dc = mh.CreateDCMotor(3);

        dc.SetSpeed(1); //tried 0 and 1
        dc.Run(Direction.Forward);

    }
```

......
`

unfortunately nothing works. perhaps you can help me.

Best regards
Florian

**Comment by mjmeans** [comment]
Are you using the master branch version (the same as what is on NuGet), or are you using the development branch. The development branch had a couple of last minute changes that didn't make it into the NuGet package.

**Comment by Foggie200** [comment]
Hi,

I use the NuGet-version. I will try it using the development branch.

Thank you

Von: mjmeans [mailto:notifications@github.com]
Gesendet: Donnerstag, 22. September 2016 18:19
An: mjmeans/Adafruit.IoT <Adafruit.IoT@noreply.github.com>
Cc: Florian Liegsalz <fl@bannasch-ag.de>; Author <author@noreply.github.com>
Betreff: Re: [mjmeans/Adafruit.IoT] DC Motor not working (#2)


Are you using the master branch version (the same as what is on NuGet), or are you using the development branch. The development branch had a couple of last minute changes that didn't make it into the NuGet package.

**Comment by Foggie200** [comment]
I downloaded the developement branch but unfortunately it's still not working. Also I cannot change the speed of the stepper motor. Whatever value I set at stepper.SetSpeed(double) it is always the same. The only differences I can get are by changing the SteppingStyle. Sorry for being a nuisance.

**Comment by Foggie200** [comment]
I think the setSpeed on the Steppermotor ist not working caused by this:

`internal async Task StepAsyncInternal(int steps, Direction direction, SteppingStyle stepStyle)
        {
            double s_per_s;
            int lateststep = 0;

            var watch = System.Diagnostics.Stopwatch.StartNew();

            s_per_s = this._sec_per_step;
            if (stepStyle == SteppingStyle.Half)
            {
                s_per_s /= 2.0;
                steps *= 2;
            }
            if (stepStyle == SteppingStyle.Microstep8)
            {
                s_per_s /= this._MICROSTEPS;
                steps *= this._MICROSTEPS;
            }
            long ticksperstep = (long)(s_per_s * Stopwatch.Frequency);
            long nexttime = 0;
            for (int s=0; s<steps; s++)
            {
                lateststep = this.OneStep(direction, stepStyle);
                nexttime += ticksperstep;
                await Task.Run(() =>
                {
                    while (watch.ElapsedTicks < ticksperstep)
                    { }
                });
            }
            if (stepStyle == SteppingStyle.Microstep8)
            {
                // Always end in full step
                while ((lateststep != 0) && (lateststep != this._MICROSTEPS))
                {
                    lateststep = this.OneStep(direction, stepStyle);
                    nexttime += ticksperstep;
                    await Task.Run(() =>
                    {
                        while (watch.ElapsedTicks < ticksperstep)
                        { }
                    });
                }
            }
        }`

in your while-waiting-loop you compare ElapsedTicks with < ticksperstep. As far as I can see this, ElapsedTicks is an ongoing increasing value but ticksperstep is not increasing. you should reset the ElapsedTicks after each wait or increase the ticksperstep. I think you wanted to use the value nexttime actually

**Comment by Foggie200** [comment]
I found the errors in your DCMotor Class. This is the corrected path:

`/// <summary>
        /// Initializes a new <see cref="PwmDCMotor"/> instance.
        /// </summary>
        /// <param name="controller">The <see cref="Windows.Devices.Pwm.PwmController"/> to use.</param>
        /// <param name="driver">The motor driver channel (1 through 4) for coil A.</param>
        internal PwmDCMotor(Windows.Devices.Pwm.PwmController controller, byte driver)
        {
            this._controller = controller;
            this._motorNum = driver;
            byte pwm=0, in1=0, in2 = 0;

            if (driver == 1)
            {
                pwm = 8;
                in2 = 9;
                in1 = 10;
            }
            else if (driver == 2)
            {
                pwm = 13;
                in2 = 12;
                in1 = 11;
            }
            else if (driver == 3)
            {
                pwm = 2;
                in2 = 3;
                in1 = 4;
            }
            else if (driver == 4)
            {
                pwm = 7;
                in2 = 6;
                in1 = 5;
            }
            else
                throw new MotorHatException("MotorHat Motor must be between 1 and 4 inclusive");

            this._PWMpin = this._controller.OpenPin(pwm);
            this._IN1pin = this._controller.OpenPin(in1);
            this._IN2pin = this._controller.OpenPin(in2);

            this._PWMpin.Start();
            this._IN1pin.Start();
            this._IN2pin.Start();

        }

        /// <summary>
        /// Runs the motor in the specified direction.
        /// </summary>
        /// <param name="command">A <see cref="Direction"/>.</param>
        /// <remarks>
        /// This method uses the previously value set using <see cref="SetSpeed(double)"/> to modulate the PWM power going to the motor.
        /// In order to change the speed of a running motor you must call this method again after calling <see cref="SetSpeed(double)"/>.
        /// </remarks>
        public void Run(Direction command)
        {
            if (this._controller == null)
                return;

            if (command == Direction.Forward)
            {
                this._PWMpin.SetActiveDutyCyclePercentage(_speed);
                this._IN2pin.SetActiveDutyCyclePercentage(0);
                this._IN1pin.SetActiveDutyCyclePercentage(1);
            }
            else if (command == Direction.Backward)
            {
                this._PWMpin.SetActiveDutyCyclePercentage(_speed);
                this._IN1pin.SetActiveDutyCyclePercentage(0);
                this._IN2pin.SetActiveDutyCyclePercentage(1);
            }
            else if (command == Direction.Release)
            {
                this._PWMpin.SetActiveDutyCyclePercentage(_speed);
                this._IN1pin.SetActiveDutyCyclePercentage(0);
                this._IN2pin.SetActiveDutyCyclePercentage(0);
            }
            else
                throw new ArgumentException("command");
        }`

**Comment by mjmeans** [comment]
I've been using the library in a live program to run a stepper motor for a couple of months. I'll double check the above code as soon as I pick up a DC motor to test and verify with.

**Comment by mjmeans** [comment]
You're right on the stepper issue. It should be comparing against nexttime not ticksperstep. My working code that I've not yet comitted has this fix. The reason for nexttime is that IoT is not a real time OS and resetting elapsedtime upon each iteration will lose ticks. If one loop iteration is missed due to OS taking too much time in another thread we have to loop quickly for a few times in order to catch up where the stepper should be. I'll post that change to development tonight.

**Comment by mjmeans** [comment]
Okay, the development branch already had that correction for nexttime instead of ticksperstep.

**Comment by Foggie200** [comment]
Hi, sorry for the inconvenience. I was absolutely sure that I took the developement branch. I am very sorry. I copied the code and will try it immediately.

**Comment by Foggie200** [comment]
OK, I converted to the developement branch. the new features with ie stoping the motor are great. Unfortunately I still cannot change the speed of the motor. Whatever I put in it is always using the same speed. Can you actually change the speed on your environment?

Best regards
Florian

**Comment by mjmeans** [comment]
I've pushed the updates to development. Thanks for the help.

**Comment by mjmeans** [comment]
I will have to trace the problem. I'm sure it has to do with the change from .Start and .Stop to ._PWMpin.SetActiveDutyCyclePercentage. I will look at the Motor Hat schematic today and possibly wire up a DC motor to test it.

**Comment by mjmeans** [comment]
SetDutyCyclePercentage was wrong. It should be Start and Stop. I'm adding the following comment into the class.

`            // The PCA9685 PWM controller is used to control the inputs of two TB6612FNG dual motor drivers, "IC1" and "IC3".
            // Each TB6612FNG has two motor drivers. So we have motor driver circuits of IC1a, IC1b, IC3a and IC3b.
            // These correspond to motor hat screw terminals M1, M2, M3 and M4.
            // Each driver circuit ("IC1a", etc.) has one PWM pin and two IN pins.
            // The PWM pin expects a PWM input signal. The two IN pins expect a logic 0 or 1 input signal.
            // The variables pwm, in1 and in2 variables identify which PCA9685 PWM output pins will be used to drive this PwmDCMotor.
            // The pwm variable identifies which PCA9685 output pin is used to drive the xPWM input on the TB6612FNG.
            // And the in1 and in2 variables are used to specify which PCA9685 output pins are used to drive the xIN1 and xIN2 input pins of the TB6612FNG.
`

**Comment by mjmeans** [comment]
Once I test and confirm that this works with an actual DC motor, I will move the changes to master and update the NuGet package.

**Comment by Foggie200** [comment]
Actually I think SetDutyCycle is the correct function. You need to start all 3(!) pwm ports and then change the values. Until now, you are not opening the pwnpin and if you just start and stop pwm1 and pwm2 there are no (or just default) values set and. But the active pins need to be 1. 

Just as small comment: My code is actually live tested on a real dcMotor and it is working.

**Comment by mjmeans** [comment]
In input pins on the motor drivers IN1A, IN2A, IN1B and IN2B are all logic level inputs. Take a look at this [https://cdn-shop.adafruit.com/datasheets/TB6612FNG_datasheet_en_20121101.pdf](https://cdn-shop.adafruit.com/datasheets/TB6612FNG_datasheet_en_20121101.pdf). When you use SetDutyCycle you are setting the PWM duty cycle. The driver ship expects a PWM signal ONLY on the PWM pins. The Adafruit Hat has a 16-channel PWM chip instead of a 4-channel PWM chip and a separate I2C 8-bit I/O chip. So that means that 2 PWM output pins from the PWM chip are wired to digital inputs on the motor drivers and should be used to simulate digital outputs. If you look at the python sample code that Adafruit provides you will see the same thing. They set these pins to full on or full off. They don't use the PWM.

So since the PWM outputs should simulate a logic level without PWM, the active duty cycle should be set to max so that that there are no pulses at all. Then Start should turn it on and Stop should turn it off. If that's not what is happening then I have to look into opening a bug in Microsoft.IoT.Devices.

Start and Stop should be very fast I2C commands. The SetDutyCycle command will be much slower.

**Comment by mjmeans** [comment]
So I've looked into Microsoft.IoT.Devices and it appears that Start and Stop cause IPwmControllerProvider.EnablePin and IPwmControllerProvider.DisbalePin to writing 5 bytes instead of 1. Not sure why. Only the first byte is needed, it has the flag to start and stop the PWM and set the output high or low. In contrast SetDutyCycle is calling IPwmControllerProvider.SetPulseParameters which is writing 5 bytes and that seems correct. It however, is not reading the parameters to know if they actually need to be changed which is probably okay for performance reasons, not okay if multiple programs will be reading-writing to the controller.

If SetDutyCycle is working for you, go ahead and use that. I don't know if that will actually cause any PWM pulses to appear on the input lines of the motor driver inputs or whether they safely tolerate a PWM signal in the binary inputs. I will have to find an a o-scope and check the signals.

**Comment by Foggie200** [comment]
Tank you for all your explanation. Just a thought that popped to my mind during your explanation. If we need only binary signals on in1 and in2 why are we using an pwmPin at all? Wouldn't it be enough if we just use normal pin and set its values to high and low? I know adafruit uses pwm's in the python sample, but is it really necessary?

Am 29.09.2016 um 00:02 schrieb mjmeans <notifications@github.com<mailto:notifications@github.com>>:


So I've looked into Microsoft.IoT.Devices and it appears that Start and Stop cause IPwmControllerProvider.EnablePin and IPwmControllerProvider.DisbalePin to writing 5 bytes instead of 1. Not sure why. Only the first byte is needed, it has the flag to start and stop the PWM and set the output high or low. In contrast SetDutyCycle is calling IPwmControllerProvider.SetPulseParameters which is writing 5 bytes and that seems correct. It however, is not reading the parameters to know if they actually need to be changed which is probably okay for performance reasons, not okay if multiple programs will be reading-writing to the controller.

If SetDutyCycle is working for you, go ahead and use that. I don't know if that will actually cause any PWM pulses to appear on the input lines of the motor driver inputs or whether they safely tolerate a PWM signal in the binary inputs. I will have to find an a o-scope and check the signals.

-

**Comment by mjmeans** [comment]
Why use PwmPin? Because that's what is in the Adafruit MotorHat. The PCA9685 is a 16 channel PWM controller. Each three PWM outputs are wired to three motor driver inputs (one PWM, and two INs). And the underlying code in the PwmController class is supposed to set the totem pole mode status bit for the requisite pin to set it high or low when using Start and Stop, thus bypassing the PWM duty cycle.

**Comment by Foggie200** [comment]
Ah ok, the pins we are opening are not on the raspberry but on the motorshield. I got that confused. Thanks for explaning.

Are you sure start and stop are supposed to set the status bit? The MSDN just says about start “Starts the PWM on this pin” (https://msdn.microsoft.com/de-de/library/windows/apps/windows.devices.pwm.pwmpin.start). I would expect that on start the actual PWN signal is emitted on the pin and on stop nothing is emitted any more. I would expect that it would not determine the frequency used. That is what setActiveDutyCyclePercentage is for. The question for me is whether if I set the ActiveDutyCycle before opening the Port will it still be the assigned value? If this would be the case, we could set the PWMValue to 1 on the init and then just work with start/stop.

You are absolutely right. If start sets the PWM to full, it would be enough. I will try that.

Von: mjmeans [mailto:notifications@github.com]
Gesendet: Donnerstag, 29. September 2016 07:56
An: mjmeans/Adafruit.IoT <Adafruit.IoT@noreply.github.com>
Cc: Florian Liegsalz <fl@bannasch-ag.de>; Author <author@noreply.github.com>
Betreff: Re: [mjmeans/Adafruit.IoT] DC Motor not working (#2)


Why use PwmPin? Because that's what is in the Adafruit MotorHat. The PCA9685 is a 16 channel PWM controller. Each three PWM outputs are wired to three motor driver inputs (one PWM, and two INs). And the underlying code in the PwmController class is supposed to set the totem pole mode status bit for the requisite pin to set it high or low when using Start and Stop, thus bypassing the PWM duty cycle.

**Comment by mjmeans** [comment]
I found an issue in [https://github.com/jbienzms/iot-devices/blob/master/Lib/Microsoft.IoT.Devices/Pwm/PCA9685.cs](https://github.com/jbienzms/iot-devices/blob/master/Lib/Microsoft.IoT.Devices/Pwm/PCA9685.cs). You are right, Start and Stop should start and stop the PWM and that should call the framework IPwmControllerProvider.EnablePin and IPwmControllerProvider.DisablePin. The DisablePin call is only defined in the Framework as disabling the PWM. It doesn't define whether it is should be disabled in the HIGH or LOW state. Currently the DisablePin is call is setting the PCA9685 pins register "full off" bit and clearing the 4 MSBs of the duty cycle. But what's worse is the EnablePin call seems to be clearing the "full off" bit and also clearing the its duty cycle and the duty cycle of the next higher pin! I have to do some more checking to be sure.

**Comment by mjmeans** [comment]
I've also confirmed that the PWM controller will pulse the way the driver is written now and you set it to 100% (1.0). This is because the PWM controller has two 12-bit registers for each pin. The first one holds the on count and the second holds the off count. The internal counter of the PWM continuously counts from 0 to 4095. The driver right now sets 100% to start ON at count 0 and start OFF at count 4095. So it actually ticks off for 1/4096th of a cycle.

The solution that problem is to change the PCA9685ControllerProvider class to detect when 100% duty cycle is specified and use the full ON or full OFF bits corresponding to the invertPolarity parameter.

The .NET micro framework [here](https://github.com/NETMF/netmf-interpreter/blob/dev/Framework/Core/Windows/Devices/Pwm/PwmPin.cs) says Start will call EnablePin and SetPulseParameters. Stop will call DisablePin. SetActiveDutyCyclePercentage saves the duty cycle for a future Start call, or will call SetPulseParameters if the pin is already started.

So, after the PCA9685ControllerProvider is fixed to properly handle the 100% duty cycle, we change the ctor PwmDCMotor INx pins to call OpenPin(); then SetActiveDutyCycle(1); then Polarity = ActiveLow; then Start. And then in Run() we just set the Polarity to ActiveLow or Active High.

I've pushed these changes to development but I haven't tested it yet.

**Comment by Foggie200** [comment]
Looks greate. Thanks for all your work. I could not test it ether by now, but I think one last line is missing. In DCMotor in

        internal PwmDCMotor(Windows.Devices.Pwm.PwmController controller, byte driver)

at the end PWNPin needs to be started. Otherwise no signal is send on this port

**Comment by mjmeans** [comment]
Yes you're right. I also made a small change to EnsureInitialized to make it async that I just pushed in. This should help if you have a lot of UI going on.

**Comment by mjmeans** [comment]
And yet one more small math change I just posted so that duty cycle is first converted to a count value of 0 to 4096 and that value is used for detecting 0% and 100%. This will prevent a very small duty cycle from setting both the ON and OFF count to 0 (which is not allowed) and instead set the full OFF bit. And will also prevent a very large but less than 100% value from setting an OFF value to 4095 when the it should instead set the full ON bit. i.e. duty cycle of 99.99% over 4096 counts would be 4095.59 which should really be processed as 4096 or full ON instead of 4095.

**Comment by mjmeans** [comment]
Since these changes were to the underlying PCA9685 classes I need to check both stepper motor and dc motor operation. I was able to do preliminary tests on the stepper motor support. I plan to do further tests tomorrow.

**Comment by PhilipNelson350** [comment]
Hi I am also having issues trying to run a DC motor. 
Firstly If I try and instantiate a Motor using:
mh = new MotorHat2348(0x60);
dc = mh.CreateDCMotor(4);

I get an uncaught exception? Instantiating Motors1,2,3 is OK though.

This is in addition to the same issues that Foggie200 is experiencing; I can not get a DC Motor to work at all. I hope you can fix the issues as it will be extremely useful for model railway control.

Thanks.

**Comment by PhilipNelson350** [comment]
I have found the issue with dc=mh.CreateDCMotor(4) crashing.
In PWMDCMotor.cs class internal PWMDCMotor expects a driver parameter between 1 and 4.
However the If statements it contains deal with driver=0,1,2,3.
 Changing the if statements to 1,2,3,4 fixes the issue.

I still can't get any motors to run though!

**Comment by mjmeans** [comment]
Hi PhilipNelson350, have you downloaded the development branch? The problem you mentioned exists in the release branch version.

**Comment by Foggie200** [comment]
Are you using the master version or the nu-package?

On these the dc motor did not work for me at all but there is an developement package which has additional changes. You could try that one.

Additionally on the master version you need to use the motor-indices 0-3 as far as I remember. Not 1-4

Best regards
Florian

Am 22.10.2016 um 09:40 schrieb PhilipNelson350 <notifications@github.com<mailto:notifications@github.com>>:


Hi I am also having issues trying to run a DC motor.
Firstly If I try and instantiate a Motor using:
mh = new MotorHat2348(0x60);
dc = mh.CreateDCMotor(4);

I get an uncaught exception? Instantiating Motors1,2,3 is OK though.

This is in addition to the same issues that Foggie200 is experiencing; I can not get a DC Motor to work at all. I hope you can fix the issues as it will be extremely useful for model railway control.

Thanks.

-

**Comment by PhilipNelson350** [comment]
Hi Florian,

I have tried using both the Master and the Development branches.

I simply want to run up to 4 DC motors and not a stepper motor and I am 
finding the example projects difficult.

In the Development branch:

I have taken the code for the DC Motor example in test.cs and placed it 
within the button for the stepper motor in MainPage.cs, but it crashes 
in the MotorHat2348.cs|CreateDCMotor function on the line:

  Microsoft.IoT.DeviceHelpers.TaskExtensions.UISafeWait(EnsureInitializedAsync);

Any help would be greatly appreciated!

Phil

**Comment by Foggie200** [comment]
Hi,

I had exactly the same issue the last view days. I was able to solve it yesterday by changing the raspberry. As far as I understood the problem within my solution it was caused by a slow SD-Memory-Card. On installing the OS Windows warnend me about strange behavior using this SD-Card. I now use one of the suggested cards and now it is working...

Perhaps that could help you to
Florian

**Comment by PhilipNelson350** [comment]
Hi Florian,

After a lot of checking I have solved the errors and now the sample 
program from the development branch runs without error.

My problem had been that I2C had not been working due to selecting the 
"Direct Memory Mapped" driver, instead of the "Inbox driver"

However even though I am supplying 13.5V from a clean source, a 12V DC 
motor still will not run !

Using a multimeter should I be able to see a voltage on the M3 screw 
terminals of the 2348 board ?

As mentioned I have copied the code from Test.cs for the DC Motor into 
mainpage.cs and made a few changes to get it to run

... public MainPage()
         {
             this.InitializeComponent();
             //mh = new MotorHat2348(0x60);
             //stepper = mh.CreateStepperMotor(1, 2, 200);
             //stepper.SetSpeed(60);
             //stepper.PowerFactor = 0.25;
         }

         MotorHat2348 mh;
         PwmDCMotor motor;

         private async void button_Click(object sender, RoutedEventArgs e)
         {
             button.IsEnabled = false;
             //var watch = System.Diagnostics.Stopwatch.StartNew();
             //await stepper.StepAsync(200, Direction.Forward, 
SteppingStyle.Microstep8);
             //watch.Stop();
             //System.Diagnostics.Debug.WriteLine("Duration in seconds = 
{0}", watch.Elapsed.TotalSeconds);
             //textBlock.Text = string.Format("Actual speed = {0} rpm", 
60 / watch.Elapsed.TotalSeconds);
             mh = new MotorHat2348(0x60);
             motor = mh.CreateDCMotor(3);

             int incrementDelay = 50; // milliseconds
             double speedIncrement = 0.01;

             motor.Run(Direction.Forward);

             textBlock.Text = "Forward - Speed Up!";
             for (double i = 0; i < 1; i += speedIncrement)
             {
                 motor.SetSpeed(i);
                 await Task.Delay(incrementDelay);
             }
             textBlock.Text = "Forward - Slow Down!";
             for (double i = 1; i > 0; i -= speedIncrement)
             {
                 motor.SetSpeed(i);
                 await Task.Delay(incrementDelay);
             }

             motor.Run(Direction.Backward);

             textBlock.Text = "Backward - Speed Up!";
             for (double i = 0; i < 1; i += speedIncrement)
             {
                 motor.SetSpeed(i);
                 await Task.Delay(incrementDelay);
             }
             textBlock.Text = "Backward - Slow Down!";
             for (double i = 1; i > 0; i -= speedIncrement)
             {
                 motor.SetSpeed(i);
                 await Task.Delay(incrementDelay);
             }
             motor.Stop();
             textBlock.Text = "Stopped!";
             button.IsEnabled = true;
         }

         private void button1_Click(object sender, RoutedEventArgs e)
         {
             if (mh != null)
             {
                 mh.Dispose();
                 mh = null;
             }
             Application.Current.Exit();
         }
     }

It would be great if you could help ?

regards,

Phil

**Comment by PhilipNelson350** [comment]
Hi Florian,

I have a very good SD Card and have not had any warnings.

I have tried a few things but now it is crashing in Create PWMDCMotor on :

Windows.Devices.PWM.SetDesiredFrequency(1526);

And if I comment that out then :

this._PWMpin = this._controller.OpenPin(pwm);

Also crashes ?

Do I need to set capabilities:

    <iot:Capability Name="lowLevelDevices"/>

As trying to do so causes an error.

Any help would be much appreciated!

regards,

Phil

**Comment by Foggie200** [comment]
Hi,

Good thing you found the issue with the pwm. 

The API is created from mjmeans and we have some disagreements about the dc class. Please see several post above beginning with "I found the errors in your DCMotor Class. This is the corrected path:"

Alter your own DCMotor Class according to my post setting the SetActivePeriod-method for starting and stopping. That should bring your code to work. 

Best regards

**Comment by mjmeans** [comment]
Ok. I've made a few changes and tested it with my own DC motor (1.5v to 12v). I've added a new button to the sample app to verify that it works. And I've updated the NuGet package. Development and Master branches are now synchronized. And the online documentation is rebuilt. Please give this a try and let me know if you have any other problems.

**Comment by PhilipNelson350** [comment]
Hi,

Thanks for all the hard work, it is now working very well indeed.

regards,

Phil

**Comment by PhilipNelson350** [comment]
Hi,

After a little experimentation I have found that for Model Railway DC 
motor control, setting the frequency to 100hz is a good starting point.

e.g. mh = new MotorHat2348(0x60,100);

Thanks again,

Phil

**Comment by mjmeans** [comment]
The frequency shouldn't matter. The frequency setting is the frequency that the PWM chip PCA9685 counts from 0 to 4095 and then repeats. The driver programs the PWM to switch the output ON when the count resets to 0 and then OFF based on the duty cycle you set from 0.0 to 1.0 (0% to 100%). The frequency setting for the chip allows any frequency from 24 Hz to 1526 Hz. The frequency you set has an effect on motor torque. A quick google search shows that robot controllers will use frequencies between 1 and 100 kHz. At the top end you can have inductive heating which is associated with loss of torque. At the lower end you can have an audible whine. Torque also increases with higher frequencies. And [this](http://electronics.stackexchange.com/questions/67663/criteria-behind-selecting-pwm-frequency-for-speed-control-of-a-dc-motor) link says that most commercial PWM motor controllers use a frequency of 25 kHz to get the best torque without a noticeable whine. A frequency that the PCA9685 in the MotorHat cannot attain. Human hearing range is 20 to Hz to 20 kHz, so there is no frequency setting for the MotorHat that will be immune to audible whine in all cases. It's just going to depend on the motor you use. But to get the best torque, you should use the highest frequency you can. You will have to experiment with each motor to determine which frequencies produce the lowest amplitude whine for your application.
